[package]
name = "pico-host-usb-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-executor = { version = "0.9", features = [
  "arch-cortex-m",
  "executor-thread",
  "executor-interrupt",
  "defmt",
] }
embassy-rp = { version = "0.9.0", features = [
  "defmt",
  "unstable-pac",
  "time-driver",
  "critical-section-impl",
  "rp2040",
] }
embassy-usb = { version = "0.5.1", features = ["defmt"] }
embassy-usb-driver = { version = "0.2.0", features = ["defmt"] }
embassy-futures = "0.1.2"
embassy-time = "0.5.0"
embassy-embedded-hal = "0.3.2"
embassy-sync = { version = "0.7.2" }

cortex-m = { version = "0.7.7" }
cortex-m-rt = "0.7.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

defmt = { version = "1.0.1" }
defmt-rtt = "1.1.0"
heapless = "0.9.2"
num_enum = { version = "0.7.5", default-features = false }

scsi = "0.2.1"
embedded-sdmmc = { git = "https://github.com/Be-ing/embedded-sdmmc-rs", branch = "bisync", default-features = false, features = [
  "defmt-log",
] }


[patch.crates-io]
embassy-executor = { git = "https://github.com/LegitCamper/embassy", rev = "905148510d0c04726cb64297b2570d78ab04806c" }
embassy-rp = { git = "https://github.com/legitCamper/embassy", rev = "905148510d0c04726cb64297b2570d78ab04806c" }
embassy-usb = { git = "https://github.com/LegitCamper/embassy", rev = "905148510d0c04726cb64297b2570d78ab04806c" }
embassy-usb-driver = { git = "https://github.com/legitCamper/embassy", rev = "905148510d0c04726cb64297b2570d78ab04806c" }
embassy-futures = { git = "https://github.com/LegitCamper/embassy", rev = "905148510d0c04726cb64297b2570d78ab04806c" }
embassy-time = { git = "https://github.com/LegitCamper/embassy", rev = "905148510d0c04726cb64297b2570d78ab04806c" }
embassy-time-driver = { git = "https://github.com/LegitCamper/embassy", rev = "905148510d0c04726cb64297b2570d78ab04806c" }
embassy-embedded-hal = { git = "https://github.com/LegitCamper/embassy", rev = "905148510d0c04726cb64297b2570d78ab04806c" }
embassy-sync = { git = "https://github.com/LegitCamper/embassy", rev = "905148510d0c04726cb64297b2570d78ab04806c" }
